// Generated by Style Dictionary — do not edit. Source: tokens/color.json
package com.mk.designsystem

import androidx.compose.ui.graphics.Color

val BrandNavy = Color(0xFF0E2A47)
val BrandBlue = Color(0xFF2F6DB0)
val BrandBlueLight = Color(0xFF7FB0E0) // dark-mode lift of navy
val BrandTeal = Color(0xFF37C2B4)
val BrandTealDark = Color(0xFF1796A8) // pure teal fails contrast on light
val BrandWhite = Color(0xFFFFFFFF)
val LightPrimary = Color(0xFF0E2A47)
val LightSecondary = Color(0xFF37C2B4)
val LightError = Color(0xFFFF1A1A)
val LightSuccess = Color(0xFF4CAF50)
val LightWarning = Color(0xFFFF9800)
val LightBrandBar = Color(0xFF0E2A47) // branded top-app-bar / nav surface
val LightOnBrandBar = Color(0xFFFFFFFF)
val LightNeutral0 = Color(0xFFFFFFFF)
val LightNeutral20 = Color(0xFFC8C8C8)
val LightNeutral40 = Color(0xFF919191)
val LightNeutral60 = Color(0xFF5A5A5A)
val LightNeutral80 = Color(0xFF232323)
val LightNeutral100 = Color(0xFF000000)
val DarkPrimary = Color(0xFF7FB0E0) // navy is too dark on a dark bg
val DarkSecondary = Color(0xFF37C2B4)
val DarkError = Color(0xFFCF6679)
val DarkSuccess = Color(0xFF81C784)
val DarkWarning = Color(0xFFFFB74D)
val DarkBrandBar = Color(0xFF2D343B) // tonally-elevated dark navy bar (M3), not the bright primary-lift
val DarkOnBrandBar = Color(0xFFFFFFFF)
val DarkNeutral0 = Color(0xFF121212)
val DarkNeutral20 = Color(0xFF2C2C2C)
val DarkNeutral40 = Color(0xFF717171)
val DarkNeutral60 = Color(0xFFB0B0B0)
val DarkNeutral80 = Color(0xFFECECEC)
val DarkNeutral100 = Color(0xFFFFFFFF)
