#!/bin/bash

# Generate docs/screens.md — a full gallery of every Roborazzi snapshot, grouped by screen.
# Paths are read from the actual snapshot files, so the gallery can never drift from reality.
#
# Two steps:
#   1) ./gradlew :androidApp:recordRoborazziDebug      # (re)generate the PNGs
#   2) scripts/generate_screenshots_readme.sh          # rebuild this gallery

# Always run from project root (script lives in scripts/).
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/.." || exit 1

SNAPSHOTS_DIR="androidApp/src/test/snapshots/images"
OUTPUT_FILE="docs/screens.md"
mkdir -p "$(dirname "$OUTPUT_FILE")"

{
    echo "# UI Screenshots"
    echo ""
    echo "Auto-generated from Roborazzi screenshot tests — do not edit by hand."
    echo "Regenerate with:"
    echo ""
    echo '```bash'
    echo "./gradlew :androidApp:recordRoborazziDebug && scripts/generate_screenshots_readme.sh"
    echo '```'
    echo ""
} > "$OUTPUT_FILE"

prev_screen=""
for file in $(ls "$SNAPSHOTS_DIR"/*.png 2>/dev/null | sort); do
    filename=$(basename "$file")

    # Screen = the segment after '.screen.' (e.g. 'home' from ...screen.home.HomeScreenScreenshotTest_...).
    screen_name=$(echo "$filename" | sed -E 's/.*\.screen\.([a-z0-9]+)\..*/\1/')
    # State label = everything after 'ScreenshotTest_' (e.g. 'HomeUiState_0_light').
    state=$(echo "$filename" | sed -E 's/.*ScreenshotTest_//; s/\.png$//')
    rel_path="../$SNAPSHOTS_DIR/$filename"

    if [[ "$screen_name" != "$prev_screen" ]]; then
        [[ -n "$prev_screen" ]] && echo "" >> "$OUTPUT_FILE" && echo "" >> "$OUTPUT_FILE"
        # Capitalize the first letter for the heading.
        title="$(tr '[:lower:]' '[:upper:]' <<< "${screen_name:0:1}")${screen_name:1}"
        {
            echo "## $title"
            echo ""
        } >> "$OUTPUT_FILE"
        prev_screen="$screen_name"
    fi

    echo -n "<img src=\"$rel_path\" width=\"200\" alt=\"$screen_name — $state\" /> " >> "$OUTPUT_FILE"
done

{
    echo ""
    echo ""
    echo "---"
    echo "*Generated by \`scripts/generate_screenshots_readme.sh\`*"
} >> "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
